V3
stark-tech-space/lalamove-node pull request #9
Opened 2022-05-11 03:18 UTC by JHIH-LEI

2022-05-11 04:14 UTC, Xuan0410 requested changes
改版號

2022-05-11 04:14 UTC, Xuan0410 commented on src/index.ts
> +  stops: Array<Omit<DeliveryStop, "stopId">>;
用兩個type
```
type DeliveryStop = {...}
type DeliveryStopWithId = DeliveryStore & { stopId: string }
```

2022-05-11 04:14 UTC, Xuan0410 commented on test/index.test.ts
> +  // });
用it.skip

2022-05-11 04:14 UTC, Xuan0410 commented on src/index.ts
>  };
未使用請移除，另addresses已經不存在，可以把Languages[Market]的做法移除改成Languages一種就好了
請一併確認其他type是否未使用，未使用請移除設定
裡面混了兩種看起來很亂

2022-05-11 05:05 UTC, Xuan0410 requested changes

2022-05-11 05:05 UTC, Xuan0410 commented on src/index.ts
>      }
請把error用原本的方式包起來，直接丟出來的話還要catch error做什麼

2022-05-11 06:50 UTC, JHIH-LEI commented on src/index.ts
>      }
因為會跳錯喔。
我在測試的時候他會說response跟status是未定義的。

2022-05-11 07:23 UTC, Xuan0410 requested changes

2022-05-11 07:23 UTC, Xuan0410 commented on package.json
> +  "version": "0.5.0",
算大改，請換1.0.0

2022-05-11 07:23 UTC, Xuan0410 commented on src/index.ts
> +      ChildSingleSelect3: "TOLL_FEE_3",
還有123的是不知道是什麼意思嗎？

2022-05-11 07:23 UTC, Xuan0410 commented on src/index.ts
> +      ChildSingleSelect3: "TOLL_FEE_3",
統一下格式，ENGLISH全大寫但其他是camelcase

2022-05-11 10:38 UTC, JHIH-LEI commented on src/index.ts
> +      ChildSingleSelect3: "TOLL_FEE_3",
有的。
已經修正english

2022-05-12 02:30 UTC, Xuan0410 requested changes
type跟enum的格式要注意一下
你要想一下你會想要用到怎麼樣的package，type、enum、input、output、error throw對使用者來說是友善好用的嗎
不是好像直接全部寫一寫就結束了

2022-05-12 02:30 UTC, Xuan0410 commented on src/index.ts
> +  Hong_Kong = "HK",
香港跟別人不一樣

2022-05-12 02:30 UTC, Xuan0410 commented on src/index.ts
> +export const serviceTypeMap = {
SERVICE_TYPE_MAP

2022-05-12 02:30 UTC, Xuan0410 commented on src/index.ts
> +export const serviceTypeMap = {
SERVICE_TYPE_MAP

2022-05-12 02:30 UTC, Xuan0410 commented on src/index.ts
> +}
Taiwan給的值不是這些，放進去有用嗎？

2022-05-12 02:30 UTC, Xuan0410 commented on src/index.ts
> +export enum specialRequests {
SpecialRequest

2022-05-12 02:30 UTC, Xuan0410 commented on src/index.ts
> +  ChildMultiSelect1 = 'TOLL_FEE_1',
1. key的格式跟別的enum不一樣
2. value有重複的值請合併 （Lalabag、LalabagSUV、thermalBag，FragileGoods、FragileGood...etc）

2022-05-12 02:30 UTC, Xuan0410 commented on src/index.ts
> +export type rawQuoteRequest = Omit<QuoteRequest, 'scheduleAt'> & {
RawQuoteRequest

2022-05-12 11:59 UTC, Xuan0410 requested changes

2022-05-12 11:59 UTC, Xuan0410 commented on src/index.ts
> +export type rawDeliveryStop = Omit<DeliveryStop, 'coordinates'> & {
```suggestion
export type RawDeliveryStop = Omit<DeliveryStop, 'coordinates'> & {
```

2022-05-12 11:59 UTC, Xuan0410 commented on src/index.ts
> +>;
先留下台灣有的就好了

2022-05-12 11:59 UTC, Xuan0410 commented on src/index.ts
> +  CHILD_PURCHASE_SERVICE_2 = 'PURCHASE_SERVICE_3',
```suggestion
```

2022-05-12 11:59 UTC, Xuan0410 commented on src/index.ts
> +  THERMAL_BAG = 'THERMAL_BAG_1',
和`LALABAG`是一樣的東西

2022-05-12 11:59 UTC, Xuan0410 commented on src/index.ts
> +// export type CategoryTW = Exclude<Category, Category.FOOD_DELIVERY | Category.OFFICE_ITEM>;
刪掉

2022-05-12 11:59 UTC, Xuan0410 commented on src/index.ts
> +// export type WeightTW = Exclude<Weight, Weight.LESS_THAN_3KG>;
刪掉

2022-05-12 11:59 UTC, Xuan0410 commented on src/index.ts
> +  // ChildMultiSelect10 = 'TOLL_FEE_10',
刪掉

2022-05-13 03:39 UTC, Xuan0410 approved these changes

2022-05-13 03:42 UTC, merged